### ISSUE TITLE
Hi, sorry to bother you, I would like to ask why the left graph Lml of Figure 2 needs to be supervised by both labelled and unlabelled data?

### ISSUE THREAD

**Issue by gitlonglong** [cvlab-stonybrook/Beyond-Pixels#2]
![image](https://github.com/user-attachments/assets/07d4722f-f296-4823-9007-abed3c39b821)

**Comment by prantikhowlader** [comment]
Hi, thanks for going through the work. Lml is the loss only for the labeled images (supervised) and Lmu is the loss for the unlabeled images.
