### ISSUE TITLE
'DeepLabV3Plus' object has no attribute 'prantik_avgpool'

### ISSUE THREAD

**Issue by L190200201sunasijia** [cvlab-stonybrook/Beyond-Pixels#3]
Hi, sorry to bother you, but there is an attribute prantik_avgpool in DeepLabV3Plus in line 254(c1_avgpool = self.prantik_avgpool(c1)), that you didn't mention before

**Comment by prantikhowlader** [comment]
Hi, we have provided changes to remove the typos .

**Comment by prantikhowlader** [comment]
Hi, we have removed the typos
