### ISSUE TITLE
Question about calculate_receptive_field

### ISSUE THREAD

**Issue by SouthMaiya** [cvlab-stonybrook/Beyond-Pixels#6]
May I ask, in the following code, what are the parameters k, s, and p set based on?

def calculate_receptive_field(u,v):
    k = [3,3,3,3,3,3,3]
    s = [1,1,1,2,1,1,2]
    p =[1,1,1,1,1,1,1]
    for i in range(len(k)):
        u = -p[i]+(u*s[i])
        v = -p[i]+(v*s[i])+k[i]-1
    return u,v

**Comment by prantikhowlader** [comment]
HI

You can check the first layer of resnet. This is how the parameters of k,s and p are based on
